name: Build and publish

on:
  workflow_dispatch:
    inputs:
      devBranch:
        description: 'Development branch'     
        required: true
        default: 'dev'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build_pages:
    name: Build HTML pages
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      # TYPESENSE_HOST: typesense.acdh-dev.oeaw.ac.at
      # TYPESENSE_PORT: 443
      # TYPESENSE_PROTOCOL: https
      # TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}

    steps:
      - name: Perform checkout
        uses: actions/checkout@v7

      - name: Fetch static-app skeleton
        run: ./fetch_data_app.sh ${{ inputs.devBranch }}

      - name: set up uv (Python)
        uses: astral-sh/setup-uv@v8.1.0

      - name: Install Python dependencies
        run: |
          uv sync
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Fetch data
        run: ./build_app/shell/fetch_data.sh

      - name: Fix wrong pagination in 8th edition
        run: ./build_app/python/fix_facs_1891.py

      - name: Get imprint
        run: ./build_app/shell/dl_imprint.sh

      - name: preprocess
        run: ant -f build_app/ant/preprocess.xml

      - name: add attributes and denormalize indices
        run: |
          ./build_app/shell/attributes.sh
          ./build_app/shell/denormalize.sh

      - name: Fix TEI
        run: ant -f build_app/ant/fixtures.xml

      - name: Build
        run: ant -f build_app/ant/build.xml

      - name: Generate JSON for charts
        run: ./build_app/python/generate_graphics_json.py

      #- name: Preprocess data for Typesense
      #  run: |
      #    ant -f build_app/ant/fixtures.xml
      #- name: Build Typesense Index
      #  run: |
      #    python build_app/python/make_ts_index.py
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
